import { randomAsHex } from "@polkadot/util-crypto";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import getProvider from "../lib/getProvider";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Credential Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Gateway to Blockchain</h1>

        <p className={styles.description}>
          Check out and claim credentials inside <br /> Click below!
        </p>

        <div>
          <Link href="/credentials" passHref>
            <button className={styles.button}>Enter Credential Browser</button>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://www.kilt.io/" target="_blank" rel="noopener noreferrer">
          Powered by Kilt
        </a>
      </footer>
    </div>
  );
}
